.\" Written by Ivana Varekova <varekova@redhat.com>.
.TH LOGWATCH.CONF 5 2010-02-10 "GNU" "Linux Programmer's Manual"
.SH NAME
logwatch.conf, ignore.conf, override.conf - logwatch configuration files
.SH DESCRIPTION

.BR logwatch.conf
- (
.BR /etc/logwatch/conf/logwatch.conf
)
- can contain the local configuration options.
The list of valid settings and their default values are in
.BR /usr/share/logwatch/default.conf/logwatch.conf.

.BR ignore.conf
- (
.BR /etc/logwatch/conf/ignore.conf
)
is the list of regular expressions.
The set of logs decribed by this set is ignored by logwatch.

.BR override.conf
- (
.BR /etc/logwatch/conf/override.conf
)
contains the settings which overrides the standard configuration
of specific log files or services. The syntax is the same as in
log/service files.

.SH FILES
.I /etc/logwatch/conf/logwatch.conf
.I /etc/logwatch/conf/logwatch.conf
.I /etc/logwatch/conf/logwatch.conf
.I /usr/share/logwatch/default.conf/logwatch.conf

.SH "SEE ALSO"
.BR logwatch (8)
